l_english:
 tank_designer_early_armor_train:0 "Artillery Train Car"
 tank_designer_early_armor_train_aa:0 "Artillery Train Car"
 tank_nsb_armor_upgrade:0 "Armor"
 group_train_combat_support_title:0 "Train Combat Support"
 ### EQUIPMENT MODULE CATEGORIES ###
 EQ_MOD_CAT_train_heavy_artillery_TITLE:0 "Heavy Artillery"
 EQ_MOD_CAT_train_aa_TITLE:0 "Anti-Air Gun"
 EQ_MOD_CAT_train_machineguns_TITLE:0 "Heavy Machinegun"
 EQ_MOD_CAT_train_heavy_aa_TITLE:0 "Heavy Anti-Air"
 EQ_MOD_CAT_train_carriage_type_TITLE:1 "Train Carriage"
 EQ_MOD_CAT_train_axle_type_TITLE:0 "Train Axle"
 EQ_MOD_CAT_train_special_module_TITLE:0 "Train Support Company"
 
 ### EQUIPMENT MODULE SLOTS ###
 EQ_MOD_SLOT_train_main_battery_1_TITLE:0 "Main Battery"
 EQ_MOD_SLOT_train_main_battery_2_TITLE:0 "Main Battery"
 EQ_MOD_SLOT_train_axle_type_slot_TITLE:0 "Axle Type"
 EQ_MOD_SLOT_carriage_type_slot_TITLE:0 "Carriage Type"
 EQ_MOD_SLOT_train_secondary_battery_1_TITLE:0 "Secondary Battery"
 EQ_MOD_SLOT_train_secondary_battery_2_TITLE:0 "Secondary Battery"
 EQ_MOD_SLOT_train_special_module_1_TITLE:0 "Special Features"
 EQ_MOD_SLOT_train_special_module_2_TITLE:0 "Special Features"
 ### EQUIPMENT MODULES ###
 train_flat_bed:0 "Flat Bed"
 train_open_top:0 "Open Top"
 train_enclosed_car:0 "Enclosed Car"
 train_1_wheel_axle:0 "Single-Wheel Axle"
 train_2_wheel_axle:0 "Dual-Wheel Axle"
 train_smoothbore_cannon:0 "Smoothbore Cannon"
 train_siege_gun_0:0 "Early Siege Gun"
 train_siege_gun_1:0 "Basic Siege Gun"
 train_siege_gun_2:0 "Improved Siege Gun"
 train_siege_gun_3:0 "Advanced Siege Gun"
 train_siege_gun_4:0 "Late Siege Gun"
 train_siege_gun_5:0 "Modern Siege Gun"
 train_aa_1:0 "Early Heavy Anti-Air"
 train_aa_2:0 "Basic Heavy Anti-Air"
 train_aa_3:0 "Improved Heavy Anti-Air"
 train_aa_4:0 "Advanced Heavy Anti-Air"
 train_aa_5:0 "Late Heavy Anti-Air"
 train_light_aa_1:0 "Early Anti-Air"
 train_light_aa_2:0 "Basic Anti-Air"
 train_light_aa_3:0 "Improved Anti-Air"
 train_light_aa_4:0 "Advanced Anti-Air"
 train_light_aa_5:0 "Late Anti-Air"
 train_machinegun_1:0 "Early Heavy Machine Gun"
 train_machinegun_2:0 "Basic Heavy Machine Gun"
 train_machinegun_2:0 "Improved Heavy Machine Gun"
 train_machinegun_3:0 "Advanced Heavy Machine Gun"
 train_machinegun_4:0 "Late Heavy Machine Gun"
 train_engineer:0 "Train Engineer Company"
 train_radio:0 "Train Signal Company"
 
 
 
 
 
 
 

