# Generates common/ideas/v54_britain_ideas.txt (British national spirits of the 1854-1857 opening).
# Run from the repository root:  pwsh tools/gen_britain_ideas.ps1
$ErrorActionPreference = 'Stop'
Set-Location (Split-Path -Parent $PSScriptRoot)

# name, picture, modifiers (modifier names verified against the upstream ideas)
$ideas = @(
    @('baltic_fleet', 'generic_coastal_navy', @('experience_gain_navy_factor = 0.15', 'naval_defense_factor = 0.05')),
    @('nightingale', 'generic_political_support', @('army_morale_factor = 0.05', 'stability_factor = 0.01')),
    @('land_transport', 'generic_army_investment', @('supply_consumption_factor = -0.05', 'army_org_factor = 0.03')),
    @('horse_guards', 'generic_army_corruption', @('planning_speed = -0.1', 'training_time_factor = 0.05', 'stability_factor = 0.01')),
    @('coalition_cabinet', 'generic_political_concessions', @('political_power_gain = 0.1', 'stability_factor = -0.02')),
    @('public_opinion', 'generic_political_support', @('war_support_factor = 0.05', 'political_power_gain = 0.03')),
    @('manchester_school', 'generic_neutrality_drift_bonus', @('war_support_factor = -0.05', 'trade_opinion_factor = 0.1')),
    @('palmerston_ministry', 'generic_political_support', @('war_support_factor = 0.1', 'political_power_gain = 0.05', 'stability_factor = 0.02')),
    @('prince_albert', 'generic_political_support', @('research_speed_factor = 0.03', 'stability_factor = 0.02')),
    @('free_trade', 'generic_economic_increase', @('trade_opinion_factor = 0.1', 'industrial_capacity_factory = 0.05')),
    @('shipyards', 'generic_coastal_navy', @('industrial_capacity_dockyard = 0.1', 'production_speed_dockyard_factor = 0.1')),
    @('limited_liability', 'generic_bank', @('production_speed_infrastructure_factor = 0.05', 'tax_efficiency_factor = 0.02')),
    @('coal_and_iron', 'generic_rapid_industrialisation', @('industrial_capacity_factory = 0.05', 'production_factory_max_efficiency_factor = 0.05')),
    @('merit_commissions', 'generic_army_war_college', @('army_org_factor = 0.05', 'experience_gain_army_factor = 0.1', 'stability_factor = -0.02')),
    @('steam_navy', 'generic_coastal_navy', @('experience_gain_navy_factor = 0.1', 'industrial_capacity_dockyard = 0.05')),
    @('gunboats', 'generic_coastal_navy', @('production_speed_dockyard_factor = 0.05', 'naval_defense_factor = 0.05')),
    @('staff_college', 'generic_army_war_college', @('planning_speed = 0.1', 'max_planning = 0.05')),
    @('expeditionary_army', 'generic_army_investment', @('army_attack_factor = 0.03', 'supply_consumption_factor = 0.05')),
    @('crimean_winter', 'generic_army_problems', @('army_org_factor = -0.05', 'supply_consumption_factor = 0.1', 'war_support_factor = -0.03')),
    @('army_scandal', 'generic_army_corruption', @('political_power_gain = -0.1', 'stability_factor = -0.03')),
    @('income_tax_doubled', 'generic_bank', @('tax_efficiency_factor = 0.08', 'stability_factor = -0.02')),
    @('civil_service_reform', 'generic_political_support', @('political_power_gain = 0.05', 'tax_efficiency_factor = 0.02')),
    @('tenant_right', 'generic_political_concessions', @('stability_factor = 0.02', 'tax_efficiency_factor = -0.01')),
    @('paris_declaration', 'generic_neutrality_drift_bonus', @('trade_opinion_factor = 0.05')),
    @('sanitary_reform', 'generic_political_support', @('stability_factor = 0.02')),
    @('victoria_cross', 'generic_army_investment', @('army_morale_factor = 0.03')),
    @('bessemer', 'generic_rapid_industrialisation', @('production_factory_max_efficiency_factor = 0.05', 'industrial_capacity_factory = 0.03'))
)

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine('# Victorian 1854-1900 project: British national spirits of the 1854-1857 opening (generated by tools/gen_britain_ideas.ps1).')
[void]$sb.AppendLine('ideas = {')
[void]$sb.AppendLine("`tcountry = {")
foreach ($i in $ideas) {
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("`t`tENG_v54_idea_$($i[0]) = {")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("`t`t`tallowed = { always = no }")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("`t`t`tallowed_civil_war = {")
    [void]$sb.AppendLine("`t`t`t`talways = yes")
    [void]$sb.AppendLine("`t`t`t}")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("`t`t`tremoval_cost = -1")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("`t`t`tpicture = $($i[1])")
    [void]$sb.AppendLine('')
    [void]$sb.AppendLine("`t`t`tmodifier = {")
    foreach ($m in $i[2]) { [void]$sb.AppendLine("`t`t`t`t$m") }
    [void]$sb.AppendLine("`t`t`t}")
    [void]$sb.AppendLine("`t`t}")
}
[void]$sb.AppendLine("`t}")
[void]$sb.AppendLine('}')
[IO.File]::WriteAllText('common/ideas/v54_britain_ideas.txt', ($sb.ToString() -replace "`r`n", "`n"), (New-Object Text.UTF8Encoding $false))
"{0} ideas written" -f $ideas.Count
